{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.4.jar",
          "url": "spring-webmvc-6.1.4.jar",
          "size": 1047572,
          "sha512": "b1331e9c034d106221fc682e541cae77272a238864730536c3a7d984d0cb2e996e3019548424c49481dd15c8c8ba7bc5fad09426215cef76bdb179f69aed8a8b",
          "sha256": "340c2ccaff0162156920b5526e8d477ebf7718f8f4df111ab7d5156c36de6547",
          "sha1": "e7aad7c53e05c8772209e915029e121262a7bc33",
          "md5": "00ea7cdb086d0a0b38b8637d63e49285"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.4.jar",
          "url": "spring-webmvc-6.1.4.jar",
          "size": 1047572,
          "sha512": "b1331e9c034d106221fc682e541cae77272a238864730536c3a7d984d0cb2e996e3019548424c49481dd15c8c8ba7bc5fad09426215cef76bdb179f69aed8a8b",
          "sha256": "340c2ccaff0162156920b5526e8d477ebf7718f8f4df111ab7d5156c36de6547",
          "sha1": "e7aad7c53e05c8772209e915029e121262a7bc33",
          "md5": "00ea7cdb086d0a0b38b8637d63e49285"
        }
      ]
    }
  ]
}
